language: node_js
node_js:
  - "8"
before_install: npm install -g grunt-cli codecov istanbul
install: npm install
before_script: grunt build
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha ./test/**/*.js --reporter
  - codecov
deploy:
     provider: releases
     api_key:
         secure: $DEPLOY_TOKEN
     file:
         - build/policr.zip
     skip_cleanup: true
     on:
         repo: LoooooKe/policr
         tags: true